### ISSUE TITLE
show expected amount of credits needed in prepare.py step

### ISSUE THREAD

**Issue by emileaben** [emileaben/ixp-country-jedi#3]
Prepare.py could show the expected number of credits needed because it knows how many IPv4 and how many IPv6 addresses there are and just needs to deduce from that how many measurements there are and multiply by one-off traceroute msm cost (60 credits currently)

**Comment by pgigis** [comment]
Added this functionality on my new pull request.

I saw the following regarding the traceroute cost calculation.

Example:
Assume that you have selected 14 valid probes.

The number of total traceroute is 14*14 and not 14 * (14 - 1)
due to the fact that the probe that launch the measurment is also on the destination list.

Should we exclude it from the destination probe list?

**Comment by emileaben** [comment]
yes. i was lazy ;)
